using System;
using System.Collections.Generic;
using UnityEngine;

namespace DA
{
    /// <summary>
    /// Build-time registry of every Live2D model prefab, looked up by name at runtime.
    /// (Prefabs can't be loaded from loose .prefab files in a player build, so we keep
    /// hard references here; generated by DA_Build.BuildRegistry.)
    /// </summary>
    [CreateAssetMenu(menuName = "DA/Model Registry")]
    public class ModelRegistry : ScriptableObject
    {
        [Serializable]
        public struct Entry
        {
            public string name;
            public GameObject prefab;
        }

        public List<Entry> entries = new List<Entry>();

        private Dictionary<string, GameObject> _map;

        public IEnumerable<string> Names
        {
            get { foreach (var e in entries) yield return e.name; }
        }

        public GameObject Get(string name)
        {
            if (_map == null)
            {
                _map = new Dictionary<string, GameObject>(entries.Count);
                foreach (var e in entries) if (e.prefab != null) _map[e.name] = e.prefab;
            }
            return _map.TryGetValue(name, out var p) ? p : null;
        }

        public static ModelRegistry Load()
        {
            return Resources.Load<ModelRegistry>("ModelRegistry");
        }
    }
}
